### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by haydenbleasel**

### CODE REVIEW

**Review by Remi-dee — COMMENTED** [review]
The changes made fixed the error, thank you so much!
Btw, is the rename to `lib` neccesary or serve any purpose?

**Comment by haydenbleasel** [comment]
> The changes made fixed the error, thank you so much! Btw, does the `lib` directory serve any purpose?

No problem, happy I could help!

No, the `lib` folder isn't special, it's just a common pattern for storing "library" or "utility" files. You can rename this if you'd like.

Also, would you mind marking [this comment](https://github.com/vercel/next.js/discussions/48585#discussioncomment-5677374) as the accepted answer on our discussion? Thanks 😄

**Comment by Remi-dee** [comment]
> > The changes made fixed the error, thank you so much! Btw, does the `lib` directory serve any purpose?
> 
> No problem, happy I could help!
> 
> No, the `lib` folder isn't special, it's just a common pattern for storing "library" or "utility" files. You can rename this if you'd like.
> 
> Also, would you mind marking [this comment](https://github.com/vercel/next.js/discussions/48585#discussioncomment-5677374) as the accepted answer on our discussion? Thanks 😄

**Comment by Remi-dee** [comment]
> > The changes made fixed the error, thank you so much! Btw, does the `lib` directory serve any purpose?
> 
> No problem, happy I could help!
> 
> No, the `lib` folder isn't special, it's just a common pattern for storing "library" or "utility" files. You can rename this if you'd like.
> 
> Also, would you mind marking [this comment](https://github.com/vercel/next.js/discussions/48585#discussioncomment-5677374) as the accepted answer on our discussion? Thanks 😄

Sure, i'll gladly do that, i'll also give you a follow here and i'll love to connect with you if you don't mind that haha.

**Comment by haydenbleasel** [comment]
> Sure, i'll gladly do that, i'll also give you a follow here and i'll love to connect with you if you don't mind that haha.

Sure thing! I'm most active on [Twitter](https://twitter.com/haydenbleasel) and here on GitHub.

**Pull request closed without merging**
